# Project Euler
# Even Fibonacci Numbers
# Problem 2
# https://projecteuler.net/problem=2
#
# """
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# """

fib, sum = [1,1], 0
while fib[-1] < 4000000:
  fib.append(fib[-1]+fib[-2])
for item in fib:
  if item % 2 == 0:
    sum += item
print(sum)
