% Project Euler
% Even Fibonacci Numbers
% Problem 2
% https://projecteuler.net/problem=2
% 
% """
% Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
% By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
% """

fib = [];

var = 0; % Use as an index

while true
    nextFib = fibonacci(var);
    if nextFib > 4000000
        break;
    end
    fib(end + 1) = nextFib;
    var = var + 1;
end

var = 0; % Reusing variable as sum

for x = fib
  if ~ mod(x,2)
    var = var + x;
  end
end

var
